name: landcover-win
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - scikit-image
  - tifffile
  - pyyaml
  - pip
  - pip:
      - tensorflow==2.11.0
      - tensorflow-addons==0.19.0
