---

# YAML configuration file for train.py

seed: 42
batch_size: 8
epochs: 2
lr: 0.001

# dossier qui contient train/images, train/masks, test/images
dataset_folder: 'data/dataset'

# dossier (RELATIF) où les expériences seront stockées
xp_rootdir: 'experiments'

# pas de fichier de validation imposé
val_samples_csv: null
