seed: 42

data:
  root: dataset/
  batch_size: 32
  num_workers: 4
  val_samples_csv: null

augmentations:
  hflip: true
  vflip: true
  rotate: true

model:
  name: unet
  num_layers: 4
  base_filters: 64
  upconv_filters: 96

loss:
  name: ce_global_kl
  class_weights: [0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 3.0, 6.0, 1.3]
  ignore_index: null
  exclude_classes: [0, 1]
  eps: 1.0e-8
  smooth: 1.0e-6
  kl_weight: 0.05
  dice_weight: 0.3

training:
  epochs: 30
  lr: 0.001
  weight_decay: 1.0e-4
  lr_patience: 8
  lr_factor: 0.5
  xp_rootdir: experiments
  xp_name: null
