seed: 42

data:
  root: ../data/dataset

model:
  name: unet
  num_layers: 2
  base_filters: 64
  upconv_filters: 96

inference:
  batch_size: 32
  num_workers: 4
  xp_rootdir: experiments
  xp_name: last  # or specific run dir name
  checkpoint_epoch: 1
  set: test  # train | val | test
  output_csv: null  # optional override path
  eps: 1.0e-8
