seed: 42

data:
  root: ../data/dataset
  batch_size: 32
  num_workers: 4
  val_samples_csv: null

augmentations:
  hflip: true
  vflip: true
  rotate: true

model:
  name: unet
  num_layers: 2
  base_filters: 64
  upconv_filters: 96

loss:
  name: ce_global_kl
  class_weights: null  # or "inverse_frequency"
  ignore_index: null
  exclude_classes: [0, 1]
  eps: 1.0e-8
  smooth: 1.0
  kl_weight: 1.0
  dice_weight: 1.0

training:
  epochs: 2
  lr: 0.001
  weight_decay: 0.0
  lr_patience: 20
  lr_factor: 0.5
  xp_rootdir: experiments
  xp_name: null
