name: landcover-torch
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - numpy
  - pandas
  - pyyaml
  - tqdm
  - matplotlib
  - scikit-learn
  - tensorboard
  - tifffile
  - opencv
  - albumentations
  - pip:
      - rich
